[package]
name = "to-do-list"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
egui = "0.22"
eframe = "0.22"
winapi = { version = "0.3", features = ["winuser"] }